# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 14:03
from __future__ import unicode_literals

import ctalk.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClgCourseDepart',
            fields=[
                ('clg_cd_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeDetail',
            fields=[
                ('college_id', models.IntegerField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=100, unique=True)),
                ('college_address', models.CharField(max_length=100)),
                ('college_pic', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('desig_id', models.IntegerField(primary_key=True, serialize=False)),
                ('desig_name', models.CharField(max_length=50, unique=True)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupDetail',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('no_of_member', models.IntegerField()),
                ('creation_date', models.DateField()),
                ('allow_msg', models.IntegerField()),
                ('notification', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCourse',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDepart',
            fields=[
                ('depart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('enroll_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=30, unique=True)),
                ('contact_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('manage_by', models.CharField(blank=True, max_length=30)),
                ('registration_id', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ctalk.UserRegistration')),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePicDetail',
            fields=[
                ('enroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ctalk.UserRegistration')),
                ('pic_link', models.ImageField(blank=True, upload_to=ctalk.models.GetImageFolder)),
            ],
        ),
        migrations.AddField(
            model_name='userregistration',
            name='clg_cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctalk.ClgCourseDepart'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctalk.CollegeDetail'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='desig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctalk.Designation'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='enroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctalk.UserRegistration'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctalk.GroupDetail'),
        ),
        migrations.AddField(
            model_name='groupdetail',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctalk.UserRegistration'),
        ),
        migrations.AddField(
            model_name='clgcoursedepart',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctalk.CollegeDetail'),
        ),
        migrations.AddField(
            model_name='clgcoursedepart',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctalk.MasterCourse'),
        ),
        migrations.AddField(
            model_name='clgcoursedepart',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctalk.MasterDepart'),
        ),
    ]
